version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: