version: '3.3'

services:
  drupal:
    image: drupal:7
    ports:
      - 80:80
    volumes:
      - ./drupal/microservice:/var/www/html/sites/all/modules
      - drupal_files:/var/www/html/sites/default
    restart: always

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

  microservice:
    build: ./microservice
    volumes:
      - /home/node/app/node_modules
      - ./microservice:/home/node/app
    ports:
      - 4000:4000

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  db_data:
  drupal_files:
  redis-data: