version: '3.3'

services:
  drupal:
    image: drupal:7
    ports:
      - 80:80
    volumes:
      - drupal_files:/var/www/html
      - ./drupal/microservice:/var/www/html/sites/all/modules
      - ./drupal/settings.php:/var/www/html/sites/default/settings.php
    restart: always

  drush:
    image: drush/drush
    volumes:
      - drupal_files:/app
    depends_on:
      - drupal

  microservice:
    build: ./microservice
    volumes:
      - /home/node/app/node_modules
      - ./microservice:/home/node/app
    ports:
      - 4000:4000

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
        - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
  drupal_files: