version: '2'
services:

  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - 80:80
    environment:
      - "CONFIG_VARS=HAX_FORMS_ENDPOINT"
      - "HAX_FORMS_ENDPOINT=http://localhost:8081"

    
  hax-forms:
    image: heymp/hax-forms-service:0.1.3
    ports:
      - 8081:4000
    environment:
      - PRISMA_DB_PROVIDER=postgresql
      - PRISMA_DB_URL=postgresql://prisma:prisma@postgres/
    depends_on:
      - postgres
  
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - hax-forms-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  hax-forms-data: